spring.application.name=login
# Configuración de Base de Datos inyectada por Variables de Entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# Seguridad JWT inyectada por Variables de Entorno
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refresh-token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION}